name: Secrets Detection

on:
  workflow_call:
  

jobs:
  gitleaks-scan:
    name: Gitleaks Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

      - name: Upload Gitleaks Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

  detect-secrets:
    name: Additional Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Create secrets baseline
        run: |
          detect-secrets scan --all-files --force-use-all-plugins \
            --exclude-files '\.git/.*' \
            --exclude-files 'package-lock\.json' \
            > .secrets.baseline

      - name: Audit secrets baseline
        run: |
          detect-secrets audit .secrets.baseline || true

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: detect-secrets-baseline
          path: .secrets.baseline

  summary:
    name: Secrets Scan Summary
    runs-on: ubuntu-latest
    needs: [gitleaks-scan, detect-secrets]
    if: always()
    steps:
      - name: Summary
        run: |
          echo "##  Secrets Detection Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Scanner | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| Gitleaks |  Completed |" >> $GITHUB_STEP_SUMMARY
          echo "| Detect-Secrets |  Completed |" >> $GITHUB_STEP_SUMMARY