name: Dependency Vulnerability Scan

on:
  workflow_call:
  push:
    branches: [ main, develop ]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  snyk-scan:
    name: Snyk Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Run Snyk
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload Snyk SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      - name: Upload Snyk Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk.sarif

  owasp-dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache NVD Data
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-nvd-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-nvd-

      - name: Run OWASP Dependency Check with NVD API Key
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:check \\
            -DnvdApiKey=${NVD_API_KEY} \\
            -DfailBuildOnCVSS=11 \\
            -DskipSystemScope=true \\
            -DskipTestScope=true
        continue-on-error: true

      - name: Upload OWASP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: target/dependency-check-report.html

  snyk-monitor:
    name: Snyk Monitor
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Snyk Monitor with CLI
        continue-on-error: true
        run: |
          snyk monitor \
            --severity-threshold=medium \
            --project-name=vulnado \
            --maven

      - name: Snyk Monitor Status
        if: always()
        run: echo "Snyk monitoring completed"
