name: Container Security Scan

on:
  workflow_call:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Save Docker images
        run: |
          docker save vulnado_vulnado:latest -o vulnado.tar
          docker save vulnado_client:latest -o client.tar
          docker save vulnado_internal_site:latest -o internal.tar

      - name: Upload Docker images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            vulnado.tar
            client.tar
            internal.tar
          retention-days: 1

  trivy-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Docker images
        run: |
          docker load -i vulnado.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnado_vulnado:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Generate Trivy HTML report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnado_vulnado:latest'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-report.html'

      - name: Upload Trivy HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.html

  snyk-container-scan:
    name: Snyk Container Scan
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Docker images
        run: docker load -i vulnado.tar

      - name: Run Snyk Container Scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vulnado_vulnado:latest
          args: --severity-threshold=high --file=Dockerfile

      - name: Upload Snyk Container results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-container-report
          path: snyk.sarif

  anchore-scan:
    name: Anchore Container Scan
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Docker images
        run: docker load -i vulnado.tar

      - name: Run Anchore scan
        uses: anchore/scan-action@v3
        with:
          image: vulnado_vulnado:latest
          fail-build: false
          severity-cutoff: high

      - name: Upload Anchore scan results
        uses: actions/upload-artifact@v4
        with:
          name: anchore-report
          path: anchore-reports/

  grype-scan:
    name: Grype Vulnerability Scanner
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker images
        uses: actions/download-artifact@v3
        with:
          name: docker-images

      - name: Load Docker images
        run: docker load -i vulnado.tar

      - name: Run Grype
        uses: anchore/scan-action@v3
        with:
          image: vulnado_vulnado:latest
          output-format: sarif
          fail-build: false

      - name: Upload Grype results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif