name: Deploy Test Environment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose
        run: |
          docker compose up -d
          sleep 30

      - name: Show running containers
        run: docker compose ps

      - name: Wait for Vulnado API
        run: |
          timeout 120 bash -c 'until curl -f http://localhost:8080/actuator/health 2>/dev/null; do sleep 5; done' || true

      - name: Wait for Client
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:1337 2>/dev/null; do sleep 5; done' || true

      - name: Verify deployment
        run: |
          echo "Checking Vulnado API..."
          curl -I http://localhost:8080 || echo "API not ready"
          
          echo "Checking Client..."
          curl -I http://localhost:1337 || echo "Client not ready"
          
          echo "Checking Database..."
          docker compose ps db

      - name: Health check
        run: |
          curl -f http://localhost:8080/actuator/health || exit 1

      - name: Export Docker logs
        if: always()
        run: |
          mkdir -p logs
          docker compose logs > logs/docker-compose.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deployment-logs
          path: logs/